### ISSUE TITLE
Add new third party / new field type to FieldBuilder

### ISSUE THREAD

**Issue by littlenoah89** [Log1x/acf-builder-cheatsheet#23]
Hi there,
I'm developing a project where I need to create a specific list of svg icons selectable from an acf field.
browsing the web I came across this repo [https://github.com/agence-adeliom/acf-icon-picker](https://github.com/agence-adeliom/acf-icon-picker), but I'm trying to figure out how to use it with FieldBuilder.
Do you have any advice?
Thank you in advance,

Fabio

**Comment by Log1x** [comment]
https://github.com/Log1x/acf-builder-cheatsheet#composing-custom3rd-party-addon-fields

You'd follow this. In this case, it should be [`icon-picker`](https://github.com/agence-adeliom/acf-icon-picker/blob/master/src/fields/acf-icon-picker.php#L11).

To get the available options/config – your best bet would probably be to create the field in the backend and export it to JSON so you can see the available output. From there you can set it all with `->setConfig()`

**Comment by littlenoah89** [comment]
@Log1x Thank you so much.
Everything is working correctly.
